log:
  level: info

runner:
  file: .runner
  capacity: 1
  envs: {}
  timeout: 3h
  labels:
    - ubuntu-latest:docker://node:20-bullseye
    - ubuntu-22.04:docker://node:20-bullseye
    - laforge-2:docker://laforge-2:latest

cache:
  enabled: true
  dir: ""
  host: ""
  port: 0

container:
  # This is the key setting - ensures job containers use the gitea network
  network: laforge-2_gitea
  privileged: false
  options: ""
  workdir_parent: ""
  valid_volumes:
    - laforge-2_claude-config
  docker_host: ""

host:
  workdir_parent: ""
